import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { URLS, GET_PROJECTS_REQUEST_TIMEOUT_MS } from '../../constants/urls';
import axios, { AxiosError } from 'axios';

// Thunk for searching resources based on a search term
// A project as returned by /get-projects (Cloud Resource Manager shape):
// `name` is `projects/{projectNumber}`, `projectId` is the string ID.
export type Project = {
  projectId: string;
  name: string;
  displayName?: string;
};

export const getProjects = createAsyncThunk('projects/getProjects', async (requestData: any , { rejectWithValue, getState }) => {
  // Bumped by resetProjects (on logout) so a response arriving after the session
  // ended can be discarded instead of repopulating a cleared store.
  const epochAtStart = (getState() as any).projects?.epoch ?? 0;

  try {
    // search from your API endpoint
    axios.defaults.headers.common['Authorization'] = requestData.id_token ? `Bearer ${requestData.id_token}` : '';

    const response = await axios.get(URLS.API_URL + URLS.GET_PROJECTS, { timeout: GET_PROJECTS_REQUEST_TIMEOUT_MS });

    const data = await response.data;

    // The session can end while this request is in flight. Without this check a
    // late fulfillment would repopulate `items` and flip `isloaded` back to true
    // on a logged-out store, so the next user to log in would skip the refetch
    // and see the previous user's projects.
    if (((getState() as any).projects?.epoch ?? 0) !== epochAtStart) {
      return rejectWithValue('Aborted: session reset while request was in flight');
    }

    return data;
    //return mockSearchData; // For testing, we return mock data

  } catch (error) {
    if (error instanceof AxiosError) {
      // Tag timeouts so the bootstrap can tell "slow endpoint" from "flaky
      // request" and skip retrying — a retry would just wait the full timeout
      // again while re-running a query that walks every page of projects.
      if (error.code === 'ECONNABORTED' || error.code === 'ETIMEDOUT') {
        return rejectWithValue({ type: 'TIMEOUT', message: error.message });
      }
      return rejectWithValue(error.response?.data || error.message);
    }
    return rejectWithValue('An unknown error occurred');
  }
});

// ResourcesState defines the shape of the resources slice of the Redux state.
// It includes an array of items, a status to track loading state, and an error message
type ProjectsState = {
  items: Project[];
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | undefined | unknown | null;
  isloaded: boolean;
  /** Incremented on reset; used to discard in-flight responses from a past session. */
  epoch: number;
};

const initialState: ProjectsState = {
  items: [],
  status: 'idle',
  error: null,
  isloaded: false,
  epoch: 0,
};

// createSlice generates actions and reducers for a slice of the Redux state.
export const projectsSlice = createSlice({
  name: 'projects',
  initialState,
  reducers: {
    setIsLoaded: (state, action) => {
      state.isloaded = action.payload.isloaded;
    },
    // Clears the whole slice, including `items`. Dispatched on logout so the
    // next user never sees the previous user's projects. The epoch bump also
    // invalidates any request still in flight from the previous session.
    resetProjects: (state) => ({ ...initialState, epoch: state.epoch + 1 }),
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk.
  extraReducers: (builder) => {
    builder
      .addCase(getProjects.pending, (state) => {
        state.status = 'loading';
        state.isloaded = false;
      })
      .addCase(getProjects.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.isloaded = true;
        state.items = action.payload; // Replace the list with search results
      })
      .addCase(getProjects.rejected, (state, action) => {
        state.status = 'failed';
        state.isloaded = false;
        state.error = action.payload; // Use payload from rejectWithValue
      });
  },
});

export const { setIsLoaded, resetProjects } = projectsSlice.actions;

export default projectsSlice.reducer;
